force-app/main/default/flows/Patient_and_Provider_Creation.flow-meta.xml
=> automating record type assignment for manual flow

force-app/main/default/flows/Patient_and_Provider_Creation.flow-meta.xml
@janjulian / @SamHaberl checkout this flow update.
when a case is created and the provider id, patient id, and other cases are not closed, they are returned as results.
the flow then guides the users to exit instead of continuing to create the request.
=> update creation flow to search and return potential duplicate requests

force-app/main/default/classes/EmpiIntegration.cls, force-app/main/default/classes/EmpiIntegrationTest.cls, force-app/main/default/classes/EmpiLookup.cls, force-app/main/default/classes/EmpiLookup.cls-meta.xml, force-app/main/default/classes/Provider.cls, force-app/main/default/lwc/patientLookup/patientLookup.html, force-app/main/default/lwc/patientLookup/patientLookup.js
Adding patient lookup/adjustments
Cleanup
=> Fix dates/bugs

docs/swagger.yaml, force-app/main/default/classes/SaRestApi.cls, force-app/main/default/classes/SaRestApiTest.cls
=> ESA-32 Move phn parameter to http header.

force-app/main/default/classes/Eform.cls, force-app/main/default/classes/SarBuilder.cls
ESA-816 Add support for health questionnaire (valueCoding attribute).
ESA-716 Add support for file attachments.
=> ESA-816 and ESA-713

force-app/main/default/layouts/Case-SA Request.layout-meta.xml, force-app/main/default/objects/PersonAccount/compactLayouts/SA_Person_Account.compactLayout-meta.xml
was brought up in a discussion for ESA-1315 but not documented.  Provider ID added to case details view and compact view for providers.
=> adding provider ID to case layout and provider compact view

force-app/main/default/classes/PrescriptionHistoryResponse.cls, force-app/main/default/lwc/pharmanetHistory/pharmanetHistory.js
=> Revert "ESA-1335: Adding calc reference from back-end API"

force-app/main/default/classes/PrescriptionHistoryResponse.cls, force-app/main/default/lwc/pharmanetHistory/pharmanetHistory.js
=> Revert "Revert "ESA-1335: Adding calc reference from back-end API""

force-app/main/default/flexipages/SA_Case_Record_Page.flexipage-meta.xml
additional rearrangement of the tabs
=> update to ESA-1299

force-app/main/default/email/SA_Fax_Templates/MIR_Fax_Template.email, force-app/main/default/email/SA_Fax_Templates/Not_Approved_Fax_Template.email
adding generic response to templates
=> ESA-1498 MIR NA template updates

force-app/main/default/flows/Create_SA_Request.flow-meta.xml, force-app/main/default/layouts/Diagnosis__c-Diagnosis Layout.layout-meta.xml, force-app/main/default/layouts/Drug__c-Drug Layout.layout-meta.xml, force-app/main/default/objects/Diagnosis__c/fields/Hierarchy__c.field-meta.xml, force-app/main/default/permissionsets/SA_Administrator.permissionset-meta.xml, force-app/main/default/permissionsets/SA_Drug_Manager.permissionset-meta.xml
=> Added Hierarchy to differentiate primary and secondary diagnosis types

force-app/main/default/email/SA_Fax_Templates/Not_Approved_Fax_Template.email
Only MIR template was fixed on the latest update. This is hopefully the final update for this ticket
=> fix NA template again with generic wording ESA1498

dev-app-post/main/default/permissionsets/HIBC_CCplus_Community_User_Permission.permissionset-meta.xml, force-app/main/default/email/SA_Fax_Templates/Approved_Fax_Template.email, force-app/main/default/layouts/Case-EC Case Layout.layout-meta.xml, force-app/main/default/layouts/Case-HIBC Case Layout.layout-meta.xml, force-app/main/default/layouts/Case-SA Request.layout-meta.xml, force-app/main/default/objects/Case/fields/Max_Days_Supply__c.field-meta.xml, force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml, force-app/main/default/permissionsets/SA_Administrator.permissionset-meta.xml
Add Max Days Supply field, visible in Case Details and Approved template. Currently read-only until further dev work is done to populate from payload
=> ESA-1232 add Max Days Supply field

dev-app-pre/main/default/standardValueSets/CaseOrigin.standardValueSet-meta.xml
Updated case owner label "phone" to "Phone / Voicemail"
=> ESA-1395 changes to case origin descriptors

force-app/main/default/objects/Case/fields/Request_Type__c.field-meta.xml, force-app/main/default/objects/Case/recordTypes/Special_Authority_Request.recordType-meta.xml
Add 'switch biologic' as an option for request type to allow for reporting, and easy viewing by user.
=> ESA-1427 add "switch biologic" as Request Type

force-app/main/default/flows/Case.flow-meta.xml, force-app/main/default/layouts/Drug__c-Drug Layout.layout-meta.xml, force-app/main/default/objects/Drug__c/fields/Approval_Details__c.field-meta.xml, force-app/main/default/objects/Drug__c/fields/CDEC_Recommendation__c.field-meta.xml, force-app/main/default/objects/Drug__c/fields/Criteria_Website__c.field-meta.xml, force-app/main/default/objects/Drug__c/fields/DBC_R_R__c.field-meta.xml, force-app/main/default/objects/Drug__c/fields/Drug_Review_Results__c.field-meta.xml, force-app/main/default/objects/Drug__c/fields/Health_Canada_monograph__c.field-meta.xml, force-app/main/default/objects/Drug__c/fields/PharmaNet_RDP_code__c.field-meta.xml, force-app/main/default/objects/Drug__c/fields/Pharmacist_Notes__c.field-meta.xml, force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml, force-app/main/default/permissionsets/SA_Administrator.permissionset-meta.xml, force-app/main/default/permissionsets/SA_Drug_Manager.permissionset-meta.xml
Added multiple fields to drug layout: 
including Approval Details - this field will pull into the Rationale field in Case Details for populating into the Approved fax template
=> ESA-1210 drug layout changes

force-app/main/default/flows/Create_SA_Request.flow-meta.xml
=> Revert "ESA-1659 duplicates for all cases"

dev-app-post/main/default/permissionsets/HIBC_CCplus_Community_User_Permission.permissionset-meta.xml, dev-app-post/main/default/profiles/Admin.profile-meta.xml, dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml, force-app/main/default/classes/JsonSarBuilder.cls, force-app/main/default/classes/ODRIntegration.cls, force-app/main/default/classes/ODRIntegrationTest.cls, force-app/main/default/classes/SAApprovalRequest.cls, force-app/main/default/classes/SAApprovalRequestTest.cls, force-app/main/default/classes/SobjectSarBuilder.cls, force-app/main/default/classes/SobjectSarBuilderTest.cls, force-app/main/default/classes/SpecialAuthorityRequest.cls, force-app/main/default/classes/SpecialAuthorityRequestTest.cls, force-app/main/default/classes/TestFactory.cls, force-app/main/default/flexipages/SA_Case_Record_Page.flexipage-meta.xml, force-app/main/default/flows/Create_SA_Request.flow-meta.xml, force-app/main/default/layouts/Account-SA DEC Layout.layout-meta.xml, force-app/main/default/lwc/pharmanetPayload/pharmanetPayload.html, force-app/main/default/lwc/pharmanetPayload/pharmanetPayload.js, force-app/main/default/lwc/pnetSaForm/pnetSaForm.js, force-app/main/default/lwc/providerLookup/providerLookup.html, force-app/main/default/lwc/providerLookup/providerLookup.js, force-app/main/default/objects/Account/compactLayouts/SA_DEC_Compact.compactLayout-meta.xml, force-app/main/default/objects/Account/listViews/All_DEC_Accounts.listView-meta.xml, force-app/main/default/objects/Account/recordTypes/DEC.recordType-meta.xml, force-app/main/default/objects/Case/fields/Has_DEC__c.field-meta.xml, force-app/main/default/objects/Case/fields/Prescriber_Override_Reason__c.field-meta.xml, force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml, force-app/main/default/permissionsets/SA_Administrator.permissionset-meta.xml
ESA-385/1613 DEC lookup on flow
=> ESA-1345 End to end support for DEC manual + eForm.

force-app/main/default/flows/Create_SA_Request.flow-meta.xml
=> Revert "Activate flow."

force-app/main/default/flows/Related_Case.flow-meta.xml, force-app/main/default/quickActions/Case.Child_Case.quickAction-meta.xml
Removed two Date field updates and fixed OwnerId update
=> ESA-707d - Fix issue for MoH Standard user

force-app/main/default/flows/Create_SA_Request_HIBC.flow-meta.xml
=> Revert "Revert ESA-1871" (Bring back ESA-1871) 

force-app/main/default/quickActions/Drug__c.Update_Drug.quickAction-meta.xml
Rearranging fields in "UPDATE DRUG" Drug Details view in case.
=> ESA-1421 Updating Drug Details

force-app/main/default/lwc/pharmanetApprovalHistory/pharmanetApprovalHistory.js
Sometimes they appeared multiple times.
=> ESA-1904 SA Approval History fixed Log and Terminate columns

force-app/main/default/lwc/phnSearchResults/phnSearchResults.js
such a tiny change. Changed subject column to drug column
=> change subject to drug ESA-1893

destructiveChanges/destructiveChanges.xml, force-app/main/default/flexipages/SA_Account_Record_Page.flexipage-meta.xml, force-app/main/default/flows/Case.flow-meta.xml, force-app/main/default/flows/Create_SA_Request.flow-meta.xml, force-app/main/default/objects/Case/fields/Last_Queue_ID__c.field-meta.xml, force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml, force-app/main/default/permissionsets/SA_Administrator.permissionset-meta.xml
Preserve Last Queue ID from parent and assign to MIR Child case. Fix other issues related to the MIR Flow.
=> ESA-1728, ESA-1911a, ESA-1912, ESA-1913, ESA-1916, ESA-1919, ESA-1920 - MIR Flow and Last Queue

force-app/main/default/permissionsets/Pharmacists.permissionset-meta.xml
DBAAC fields in the case will be editable by user with this permission set.
=> ESA-1946 add permission set

.github/workflows/build-checks.yml, force-app/main/default/objects/Drug_Template__c/fields/Excluded_Plans__c.field-meta.xml, force-app/main/default/objects/Step_Action__c/fields/Excluded_Plans__c.field-meta.xml, force-app/main/default/objects/Step_Action__c/recordTypes/Pharmanet_Payload.recordType-meta.xml
Got the correct object this time (step action rather than drug template, but it's handy to have it in both places)
=> SA-104b support for biologic excluded plans

force-app/main/default/queues/Omalizumab.queue-meta.xml
Added a queue named Omalizumab
=> Add Omalizumab queue ESA-1969

force-app/main/default/email/SA_Fax_Templates/Approved_Fax_Template.email, force-app/main/default/email/SA_Fax_Templates/Currently_Approved_Fax_Template.email, force-app/main/default/email/SA_Fax_Templates/MIR_Fax_Template.email, force-app/main/default/email/SA_Fax_Templates/Not_Approved_Fax_Template.email
added return fax number to the top of the fax back templates for visibility.
=> ESA-1681 add fax number to fax templates

force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml
MoH users need permission to view/edit EC to Account field in External Committee
=> ESA-1988 permission set for EC account field

force-app/main/default/classes/HealthGateway.cls, sfdx-project.json
What the Issue is:-
1. Existing "Requested Date" Field Format is DateTime.
Changes Made:-
1. Changed DateTime Format for Requested Date to Date
Changes Made to Class:-
HealthGateway
=> Update to sfx version post release & BCMOHAM-9611

force-app/main/default/email/SA_Fax_Templates/Approved_Fax_Template.email, force-app/main/default/email/SA_Fax_Templates/Currently_Approved_Fax_Template.email, force-app/main/default/email/SA_Fax_Templates/MIR_Fax_Template.email, force-app/main/default/email/SA_Fax_Templates/Not_Approved_Fax_Template.email
Update to "classic email templates" (fax templates) with eForms URL at the top
=> fax template update SA-278

force-app/main/default/objects/Case/fields/Priority.field-meta.xml, force-app/main/default/objects/Case/listViews/Evolocumab_Queue_Case.listView-meta.xml, force-app/main/default/objects/Drug__c/listViews/Evolocumab_Queue_Drug.listView-meta.xml, force-app/main/default/objects/Step_Action__c/listViews/Evolocumab_Queue_Step_Action.listView-meta.xml, force-app/main/default/queues/Evolocumab_Queue.queue-meta.xml
Added evolocumab queue back in so it won't be over-ridden next release.
=> SA-292 Restoration of Evolocumab Queue

force-app/main/default/layouts/Case-SA Request.layout-meta.xml, force-app/main/default/objects/Case/fields/Patient_DOB_Template__c.field-meta.xml, force-app/main/default/objects/Case/fields/Patient_Date_of_Birth__c.field-meta.xml, force-app/main/default/objects/Case/fields/Patient_Identifier_Template__c.field-meta.xml, force-app/main/default/objects/Case/fields/Patient_Identifier__c.field-meta.xml, force-app/main/default/objects/Case/fields/Patient_Name_Template__c.field-meta.xml, sfdx-project.json
Updated formula for Patient Name Template field 
Object : Case
Field : Patient Name (Template)
Original Formula:     <formula>Account.Person_Full_Name__c</formula>
Updated Formula:  <formula>Contact.FirstName + &apos; &apos; +  Contact.LastName</formula>
=> Updated Patient Name Template Formula

force-app/main/default/classes/SaRestApi.cls
Added status More Information Requested to monitor E Forms response on the picklist field selection
=> Updated	More Information Requested status in REST

force-app/main/default/classes/ODRIntegration.cls
Added a New List
Updated the Callout Response
Added List of List for each 800 din no's and executed the method in loop and merged the response to fix the issue when there are more than 800 din numbers.
=> Updated DINList code to retrieve bulk records

force-app/main/default/lwc/pharmanetHistory/pharmanetHistory.js
=> Updated with the sort

.eslintignore, .gitignore, .prettierignore, dev-setup.sh
@anudishCGI @cgiSunilM @RanadheerRG @MeganWeston Please review PR.
=> Solution for git repo source tracking issue

sfdx-project.json
Incremented version for git repo issue. Please refer to the ticket BCMOHAM-9636
=> increment version

dev-app-pre/main/default/globalValueSets/SA_Type__gvs.globalValueSet-meta.xml
Add Global Value Sets to dev-app-pre folder which is used in packaging.
=> Spring 23' Release || Add Global Value Sets to dev-app-pre folder

.github/workflows/build-checks.yml, .github/workflows/create-build.yml, manifest/profiles.xml, sfdx-project.json
Update Node.js deprecated versions to avoid errors and warnings.
=> Spring 23' Release || Update Node.js and Add GVS to profile.xml

.github/workflows/deploy-to-staging.yml, force-app/main/default/globalValueSets/SA_Type__gvs.globalValueSet-meta.xml
Since the create-build jobs kicks-off only on force-app folder update. Creating this PR for the same.
=> Spring 23' Release || Update force-app folder to kickoff create-build

.forceignore, .github/workflows/deploy-to-staging.yml
Since the create-build jobs kicks-off only on force-app folder update. Creating this PR for the same.
=> Spring 23' Release || Add SA_Type to forceignore

sfdx-project.json
Updated the sfdx-project.json API version from v57.0 to v56.0
=> Updated the version number to v56

force-app/main/default/objects/Case/validationRules/Approval_Unit_Time_Limits.validationRule-meta.xml
Validation Rule Update for ESA-1835
=> Validation Rule Update for ESA-1835

sfdx-project.json
Updated the release version number to 11.0.14
=> Updated the release version

dev-app-post/main/default/profiles/Admin.profile-meta.xml
Adding field permissions to Admin profile
=> Field Permissions to Admin profile

dev-app-post/main/default/profiles/Admin.profile-meta.xml, force-app/main/default/classes/ContentTriggerHandlerTest.cls, force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/classes/ESA_cls_caseTriggerHandlerTest.cls, force-app/main/default/classes/ESA_cls_constants.cls, force-app/main/default/classes/FaxServiceTest.cls, force-app/main/default/classes/FcEmailServiceTest.cls, force-app/main/default/classes/TestFactory.cls
Test Factory and Constant class Fix_07March
=> Sat sprint1 06 march

force-app/main/default/flexipages/SA_Case_Record_Page.flexipage-meta.xml, force-app/main/default/lwc/esa_LC_displayDECInformation/esa_LC_displayDECInformation.html, force-app/main/default/lwc/esa_LC_displayDECInformation/esa_LC_displayDECInformation.js, force-app/main/default/lwc/esa_LC_displayDECInformation/esa_LC_displayDECInformation.js-meta.xml
Development Related to ESA-1703
=> Development Related to ESA-1703

dev-app-post/main/default/profiles/Admin.profile-meta.xml, force-app/main/default/classes/ESA_cls_accountTriggerHandler.cls, force-app/main/default/classes/ESA_cls_accountTriggerHandler.cls-meta.xml, force-app/main/default/classes/ESA_cls_accountTriggerHandlerTest.cls, force-app/main/default/classes/ESA_cls_accountTriggerHandlerTest.cls-meta.xml, force-app/main/default/classes/JsonSarBuilder.cls, force-app/main/default/objects/Contact/fields/ESA_Provider_Specialty__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Provider_Specialty__c.field-meta.xml, force-app/main/default/objects/PersonAccount/compactLayouts/SA_Person_Account.compactLayout-meta.xml, force-app/main/default/objects/PersonAccount/compactLayouts/SA_Provider.compactLayout-meta.xml, force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml, force-app/main/default/triggers/ESA_tgr_accountTrigger.trigger, force-app/main/default/triggers/ESA_tgr_accountTrigger.trigger-meta.xml
Development Related to ESA-1472
=> Development Related to ESA-1472

force-app/main/default/classes/ESA_cls_accountTriggerHandler.cls, force-app/main/default/classes/JsonSarBuilder.cls
=> ESA-2114 development changes

force-app/main/default/classes/JsonSarBuilder.cls
Changes related to ESA-2114 to remove whitespaces in values.
=> Changes related to ESA-2114

force-app/main/default/classes/JsonSarBuilder.cls, force-app/main/default/flexipages/SA_Case_Record_Page.flexipage-meta.xml
Development related to ESA-614 user story
=> Development related to ESA-614

force-app/main/default/objects/Account/validationRules/MoH_Standard_User_Rule.validationRule-meta.xml, force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml
Removing the patient/provider Account Name & Identifier edit access for standard user.
=> Changes for ESA-1674

force-app/main/default/layouts/Account-SA DEC Layout.layout-meta.xml
Updates the DEC account layout to include chatter tab with post function
=> ESA-2116 DEC account layout change

force-app/main/default/lwc/pharmanetApprovalHistory/pharmanetApprovalHistory.html, force-app/main/default/lwc/pharmanetApprovalHistory/pharmanetApprovalHistory.js
Added the logic for sorting and searching for SA approval history columns.
=> Changes for ESA-1408

force-app/main/default/lwc/pharmanetHistory/pharmanetHistory.js
Updating the sort functionality to resolve the DIN filter issue
=> BCMOHAM-11050-v1 || Updating the Sort Functionality

force-app/main/default/lwc/pharmanetApprovalHistory/pharmanetApprovalHistory.js
Case Insensitive changes for ESA-1408
=> Case Insensitive changes for ESA-1408

dev-app-post/main/default/classes/LightningSelfRegisterControllerTest.cls
Commented the Hard Coded Reference in the test class for the Hyperforce Migration according to the salesforce recommendation.
LightningSelfRegisterControllerTest.cls
=> BCMOHAD-15003(Hard-Coded Reference) || Commenting the Hard coded reference

force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml
Updated MOH standard user permission set
=> Feedback -Birthdate field updated to read only

force-app/main/default/classes/ODRIntegrationTest.cls
Adding this comment in the Test class just to start the Package version
=> BCMOHAD-15003(Hard-Coded-Reference) || Adding to start package version

force-app/main/default/flexipages/SA_Case_Record_Page.flexipage-meta.xml, force-app/main/default/flows/Create_SA_Request.flow-meta.xml, force-app/main/default/lwc/esa_LC_getApprovalHistory/esa_LC_getApprovalHistory.js
Esa 1316 development changes new.
=> Esa 1316 development changes

sfdx-project.json
Updating the sfdx-project to get the version number with Version 18
=> BCMOHAM-releaseversionupdate-18 || Updating the sfdx version number

force-app/main/default/classes/KeycloakRolesTranslator.cls
Apex class:
KeycloakRolesTranslator.cls
Added try/catch
Added empty checks
=> BCMOHAD-15135 || Updated with try/catch

force-app/main/default/classes/KeycloakRolesTranslator.cls
Reverts bcgov/MoH-SAT#869
Reverting it to test whether we are facing the issue:
Untracked files:
(use "git add <file>..." to include in what will be committed)
sfdx-linux-x64.tar.xz
sfdxurl.txt
nothing added to commit but untracked files present (use "git add" to track)
Error: Invalid status code: 1
at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
at ChildProcess.emit (node:events:527:28)
at maybeClose (node:internal/child_process:1092:16)
at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
code: 1
}
Error: Invalid status code: 1
at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
at ChildProcess.emit (node:events:527:28)
at maybeClose …
=> Revert "BCMOHAD-15135 || Updated with try/catch"

force-app/main/default/classes/KeycloakRolesTranslator.cls
=> Revert "Revert "BCMOHAD-15135 || Updated with try/catch""

.github/workflows/create-build.yml, sfdx-project.json
Updated the create-build.yml and sfdx-project.json
=> BCMOHAD-15135-v1 || Updated Create Build and sfdx-project.json

sfdx-project.json
Updated the sfdx-project.json with new package ID
=> BCMOHAD-15411 || updated the sfdx-project.json

force-app/main/default/classes/ODRIntegration.cls, force-app/main/default/classes/ODRIntegrationTest.cls, force-app/main/default/flexipages/SA_Case_Record_Page.flexipage-meta.xml, force-app/main/default/lwc/pharmanetHistory/pharmanetHistory.html, force-app/main/default/lwc/pharmanetHistory/pharmanetHistory.js, force-app/main/default/lwc/pnetSaForm/pnetSaForm.html, force-app/main/default/lwc/pnetSaForm/pnetSaForm.js
Development Related to User Stories, ESA-2109 and Max.Days Supply of ESA-2131
=> Development Related to ESA-2109 and Max.Days Supply of ESA-2131

.github/workflows/create-build.yml, force-app/main/default/classes/KeycloakRolesTranslatorTest.cls
create-build.yml: Removed the Commented Method for creating the package ID in sfdx-project.json
KeycloakRolesTranslatorTest.cls: Added a comment in the Test class to check the New Package ID generation
=> BCMOHAD-15411 || Updated create-build.yml and test class

sfdx-project.json
Updating the sfdx-project.json package ID to latest version
=> BCMOHAD-15411 || sfdx updated to latest

force-app/main/default/classes/ESA_cls_CaseUpdate.cls, force-app/main/default/classes/ESA_cls_CaseUpdateTest.cls, force-app/main/default/classes/ODRIntegration.cls, force-app/main/default/classes/ODRIntegrationTest.cls, force-app/main/default/classes/PharmanetSubmissionTest.cls, force-app/main/default/classes/TestFactory.cls, force-app/main/default/lwc/pharmanetHistory/pharmanetHistory.html
Negative scenario to test class and indentation
=> Negative scenario to test class

force-app/main/default/lwc/esa_LC_getApprovalHistory/esa_LC_getApprovalHistory.js
=> ESA-2216_fix_14Jul

force-app/main/default/lwc/esa_LC_getApprovalHistory/esa_LC_getApprovalHistory.js
=> ESA-2216_fix

force-app/main/default/flows/Create_SA_Request.flow-meta.xml
As part of ESA-1316, additional duplicate check's has been added to Create SA flow.
=> Duplicate check added to SA flow

force-app/main/default/sharingRules/Case.sharingRules-meta.xml
Development related to ESA-2150,2172
=> Case Sharing Rule_ESA-2150,2172

force-app/main/default/objects/Account/validationRules/MoH_Standard_User_Rule.validationRule-meta.xml
Creating pr to deactivating Account Validation rule
=> Deactivating Account Validation rule

sfdx-project.json
Updated sfdx-project.json file
=> Updating the sfdx version number

force-app/main/default/classes/ESA_cls_ExternalCommitteeTriggerHandler.cls, force-app/main/default/classes/ESA_cls_ExternalCommitteeTriggerHandler.cls-meta.xml, force-app/main/default/classes/ESA_cls_ExternalCommitteeTriggerTest.cls, force-app/main/default/classes/ESA_cls_ExternalCommitteeTriggerTest.cls-meta.xml, force-app/main/default/labels/CustomLabels.labels-meta.xml, force-app/main/default/objects/External_Committee__c/validationRules/ESA_Restrict_Committee_Type.validationRule-meta.xml, force-app/main/default/triggers/ESA_tgr_ExternalCommitteeTrigger.trigger, force-app/main/default/triggers/ESA_tgr_ExternalCommitteeTrigger.trigger-meta.xml
Development Related To ESA-738.
=> Development Related To ESA-738

config/project-scratch-def.json
Updated the project-scratch-def.json file 
As part of unit testing, object settings have been successfully applied to the scratch org.
@deepakmulamalla Please review the PR and confrim that this change is in line with the request. Thank you!
=> Updated sharingModel for scratch orgs

sfdx-project.json
Updating the sfdx-project.json package ID. Please review the PR.
=> BCMOHAD-18016: Updated sfdx-project.json

force-app/main/default/lwc/odrLookup/odrLookup.js
**Deployment Tracker:**
Updated odrLookup.js
Added the verification for patient and prescriber override reason and not allowing further if the reason is none
=> BCMOHAD-18050 || Updated the changes

force-app/main/default/lwc/esa_LC_getApprovalHistory/esa_LC_getApprovalHistory.js, force-app/main/default/lwc/saHistoryLookup/saHistoryLookup.html, force-app/main/default/lwc/saHistoryLookup/saHistoryLookup.js
Development related to ESA-2125 & ESA-2257
=> Development related to ESA-2125 & ESA-2257

force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/classes/ESA_cls_constants.cls, force-app/main/default/objects/Case/fields/ESA_Approval_Time_Unit__c.field-meta.xml, force-app/main/default/objects/Case/fields/ESA_Approval_Time__c.field-meta.xml, force-app/main/default/objects/Case/recordTypes/Special_Authority_Request.recordType-meta.xml, force-app/main/default/objects/Case/validationRules/Approval_Unit_Time_Limits.validationRule-meta.xml
=> Changes to update termination date calculation

force-app/main/default/flows/Create_SA_Request_HIBC.flow-meta.xml
Updated the Create_SA_Request_HIBC.flow to display the Patient Identifier and Account Name when a case is created through HIBC.
=> BCMOHAD-17257 || Updated the HIBC Flow

.github/workflows/build-checks.yml
=> BCMOHAD-18354 | Updating the web get command

.github/workflows/create-build.yml
Updated create-build.yml file.
Please review the PR.
=> BCMOHAD-18354-1 || Updating create-build.yml

force-app/main/default/classes/ESA_cls_sendMOMControllerTest.cls
Updates to Test Class for build error.
=> Updates to Test Class

sfdx-project.json
Please review the PR. Thank you!
=> BCMOHAD-18354-3 || Updating sfdx-project.json file with package version IDs

.github/workflows/create-build.yml
@cgiSunilM please review the PR and confirm that this change is in line with the request. Thank you!
=> BCMOHAD-18354 | update package version command to sfdx

sfdx-project.json
Updated sfdx-project.json file. 
Please review the PR. Thank you!
=> BCMOHAD-14901 || updating package version ID

.github/workflows/create-build.yml
@cgijeffolsen Please review the PR and confirm if this change is in line with Salesforce recommendations. Thank you!
=> BCMOHAD-18354 || updating flag names

sfdx-project.json
@cgijeffolsen Please review the PR.
=> BCMOHAD-18354 | package version ID

.github/workflows/deploy-to-edrdqa.yml
Added a new repository secret for deployments to EDRDQA. 
Refer to this url: https://github.com/bcgov/MoH-SAT/settings/secrets/actions
Please review the PR. Thank you!
=> BCMOHAM-14323-4 || Adding a new repository secret for deployment workflow

.github/workflows/deploy-to-edrdqa.yml, sfdx-project.json
Increment version of sfdx-project.json file
Update GitHub action workflow 'Deploy to EDRDQA'
=> BCMOHAD-14901 || Increment version of sfdx-project.json file, updating deployment workflow

sfdx-project.json
=> BCMOHAD-14901 || Update package version id

force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/classes/ESA_cls_constants.cls, force-app/main/default/objects/Case/fields/ESA_Approval_Time_Unit__c.field-meta.xml, force-app/main/default/objects/Case/fields/ESA_Approval_Time__c.field-meta.xml, force-app/main/default/objects/Case/recordTypes/Special_Authority_Request.recordType-meta.xml, force-app/main/default/objects/Case/validationRules/Approval_Unit_Time_Limits.validationRule-meta.xml
Reverting all the changes related to ESA -2107 to fix production issue.
=> Reverting ESA -2107

sfdx-project.json
=> Updating package id version for hotfix deployment

sfdx-project.json
Updated the version number in sfdx-project.json
=> updated the version number

.github/workflows/create-build.yml, force-app/main/default/classes/AdjudicationTest.cls
Updated the Yaml file and to update the sfdx-project.json file I have added the comments in the Test class
=> Updating yaml

.github/workflows/create-build.yml
Activating debug and removing code coverage and speed up the Testing of the deployment process
=> Activating debug and removing code coverage

force-app/main/default/classes/AdjudicationTest.cls
Removed the comments in the test class to run the create build yaml file.
=> Removed the comments

.github/workflows/create-build.yml, force-app/main/default/classes/AdjudicationTest.cls
Added the wait time in create yaml and added a comment
=> Adding wait time

dev-app-post/main/default/profiles/Service Account Profile.profile-meta.xml, force-app/main/default/classes/AdjudicationTest.cls
Added full name to the Profile and uncommented the comment in the test class to run the create build yaml
=> Bcmohad 18354 6

force-app/main/default/classes/AdjudicationTest.cls
Updated the **AdjudicationTest.cls** with the comment to run the create build action. To create a new package ID.
=> Added comment to create the new package ID

.forceignore, force-app/main/default/classes/AdjudicationTest.cls
Check to see the Build trigger Pass/Failure
=> BCMOHAD-14901-v3 Deployment error Fix

config/project-scratch-def.json
Adding Health Cloud capabilities 
Changing Sharing module to Private
=> BCMOHAM-14715 || Updated Scratch org definition file

.github/workflows/build-checks.yml
Replacing depricated sfdx style commands to sf style commands to be in alignment with Salesforce recommendations
=> BCMOHAM-14715 || Updating sfdx commands to sf-style commands

.github/workflows/build-checks.yml
=> BCMOHAD-18354 || Diagnosing build check issue

.github/workflows/deploy-to-edrduat.yml
-Creating new workflow for deployment of metadata to EDRDUAT 
-Adding a new repository secret for deployment workflow. Refer to this URL: https://github.com/bcgov/MoH-SAT/settings/secrets/actions
Please review the PR.
=> BCMOHAM-14323 || Create deploy-to-edrduat.yml

.github/workflows/Manual Build Check.yml
=> BCMOHAD-18354 || Create Manual Build Check.yml

.github/workflows/Manual Build Check.yml, .github/workflows/build-checks.yml, dev-setup.sh, sfdx-project.json
Assigning Health Cloud Permission set licenses to deployment user 
Updating sfdx-project.json file
=> BCMOHAD-18354-v3 || Assigning HC permission set to deployment user 

.github/workflows/build-checks.yml
Updating indentation in yaml file
=> BCMOHAD-18354 || Update build-checks.yml

.github/workflows/build-checks.yml, config/project-scratch-def.json, dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml
Sharing model changes need to be implemented to fix the build error below:
"The sharing calculation you requested can't be processed right now, because it interferes with another operation already in progress. Please try again later"
=> BCMOHAD-18354 || changing sharing model for scratch orgs

.github/workflows/Manual Build Check.yml, .github/workflows/build-checks.yml, dev-setup.sh
Adding Omni Studio Capabilities to Current Build Process
=> BCMOHAM-14715 || setting deployment user 

.github/workflows/Manual Build Check.yml, .github/workflows/build-checks.yml, dev-setup.sh, force-app/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/flows/EDRD_Change_Enrollee_Status_OnPatient.flow-meta.xml, force-app/main/default/labels/CustomLabels.labels-meta.xml, force-app/main/default/layouts/Case-EDRD Layout.layout-meta.xml, force-app/main/default/objects/CareProgramEnrollee/listViews/All_CareProgramEnrollees.listView-meta.xml, force-app/main/default/objects/Case/fields/EDRD_MOHApproved_Dosage_Unit__c.field-meta.xml, force-app/main/default/objects/Medication/listViews/All_Medications.listView-meta.xml
Changes Related to Defect Log_11Dec
=> Changes Related to Defect Log_11Dec

dev-app-pre/main/default/globalValueSets/Duration_Unit.globalValueSet-meta.xml, force-app/main/default/objects/Case/fields/EDRD_MOHApproved_Funding_Duration_Unit__c.field-meta.xml, force-app/main/default/objects/Case/recordTypes/EDRD.recordType-meta.xml, force-app/main/default/objects/Medication/fields/If_Other_specify_MaxInitiation_duration__c.field-meta.xml, force-app/main/default/objects/Medication/fields/If_Other_specify_Max_Renewal_duration__c.field-meta.xml
Adding GVS & changes to Funding Duration field
=> Adding GVS & changes to Funding Duration field

dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml, force-app/main/default/objects/Case/fields/EDRD_Additional_information__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_Case_closure_reasons__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_Drug_cost_forecast__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_Funding_duration__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_Please_specify_other__c.field-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> Changes to UAT PR

.github/workflows/Manual Build Check.yml, .github/workflows/deploy-to-edrdqa.yml, .github/workflows/deploy-to-edrduat.yml, config/project-scratch-def.json
Adding Discovery Framework feature to scratch org config file
Adding OmniStudio metadata deployment to github action worfklows
=> BCMOHAM-15308 - adding DiscoveryFramework feature

force-app/main/default/layouts/CodeSet-Code Set Layout.layout-meta.xml, force-app/main/default/layouts/CodeSetBundle-Code Set Bundle Layout.layout-meta.xml, force-app/main/default/objects/CodeSet/listViews/All_CodeSets.listView-meta.xml, force-app/main/default/objects/CodeSetBundle/listViews/All_CodeSetBundles.listView-meta.xml
Code set and codeset bundle removing Clone button and list view
=> Code set and codeset bundle 

.github/workflows/deploy-to-edrdqa.yml, .github/workflows/deploy-to-edrduat.yml
Updating deploy source commands
=> BCMOHAM-15308 || updating deploy source commands

dev-app-post/main/default/sharingRules/Account.sharingRules-meta.xml
EDRD_Staff permission change for Account. Story EDRD-379
=> EDRD_Staff permission change for Account

force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> EDRD-292 Commit

dev-app-post/main/default/settings/Security.settings-meta.xml
Disabled Xss Protection in the security- setting.xml file.
=> Security Setting Update- Enable Xss Protection Removed

dev-app-post/main/default/sharingRules/Account.sharingRules-meta.xml, force-app/main/default/applications/EDRD_APP_Case_Management.app-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> Redeployment of EDRD-379

config/project-scratch-def.json
adding HC Licence for Community Users. 
Updated file: project-scratch-def.json
=> BCMOHAM-15308 || adding HC Licence for Community Users

force-app/main/default/layouts/PersonAccount-Patient Layout.layout-meta.xml, force-app/main/default/layouts/PersonAccount-Provider Layout.layout-meta.xml
=> EDRD-292 Defect fix

force-app/main/default/lwc/lookupSearchComp/lookupSearchComp.js, force-app/main/default/lwc/providerAccountComp/providerAccountComp.js
=> Edrd 379 defectfix

force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml
=> EDRD-379 Flow commit

force-app/main/default/lwc/lookupSearchComp/lookupSearchComp.html, force-app/main/default/lwc/lookupSearchComp/lookupSearchComp.js, force-app/main/default/lwc/providerAccountComp/providerAccountComp.html
=> EDRD-379 Cosmetic changes

dev-app-post/main/default/profiles/Admin.profile-meta.xml
=> Admin Profile Class access

force-app/main/default/permissionsets/EDRD_PS_Physicians.permissionset-meta.xml
=> Omni Issue Fix EDRD-63

.github/workflows/build-checks.yml, sfdx-project.json
Adding installation link for OmniStudio managed pkg to fix Build errors for EDRD Sprint 3 Branch 
Updating sfdx-project.json file
=> BCMOHAD-18447 || adding installation link for OS managed pkg

.github/workflows/build-checks.yml, .github/workflows/deploy-to-staging.yml
-fixing the error observed during a test deployment to staging
-adding noprompt
=> BCMOHAD-18447 || cleaning up sf command

.github/workflows/Manual Build Check.yml, .github/workflows/build-checks.yml, config/project-scratch-def.json
=> BCMOHAM-15308 || hotfix for deployments of OS

force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml
Commit Christine's Change request
=> Commit Christine's Change request

force-app/main/default/classes/EDRDAccountLookupController.cls, force-app/main/default/classes/EDRDAccountLookupController_Test.cls, force-app/main/default/lwc/lookupSearchComp/lookupSearchComp.html, force-app/main/default/lwc/lookupSearchComp/lookupSearchComp.js, force-app/main/default/lwc/lookupSearchComp/lookupSearchComp.js-meta.xml, force-app/main/default/lwc/providerAccountComp/providerAccountComp.html, force-app/main/default/lwc/providerAccountComp/providerAccountComp.js, force-app/main/default/lwc/providerAccountComp/providerAccountComp.js-meta.xml
Class code change according UAT Code Quality Comment
=> Class code change according UAT Code Quality Comment

force-app/main/default/classes/EDRDAccountLookupController.cls-meta.xml, force-app/main/default/classes/EDRDAccountLookupController_Test.cls-meta.xml, force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml, force-app/main/default/lwc/lookupSearchComp/lookupSearchComp.js-meta.xml, force-app/main/default/lwc/providerAccountComp/providerAccountComp.js-meta.xml
=> Version Changed

force-app/main/default/classes/ODRIntegration.cls
Sort Order change on the Prescription History
=> BCMOHAD-20514 Sort order change Prescription History

.github/workflows/deploy-to-build.yml, sfdx-project.json
-Updating deprecated sfdx commands to sf as per Salesforce best practices. 
-Incrementing package version.
=> BCMOHAD-18447 || replacing sfdx depricated commands

force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml
=> EDRD-545 UAT Defectfix

force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml, force-app/main/default/objects/MedicationRequest/fields/Other_Medication_Detail__c.field-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> EDRD-446 And EDRD-438 Stories

force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml
Create EDRD Case Flow Link Edit
=> Create EDRD Case Flow Link Edit

force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/labels/CustomLabels.labels-meta.xml
=> EDRD-382 Story Build Changes

.github/workflows/deploy-to-edrdqa.yml, .github/workflows/deploy-to-edrduat.yml
=> BCMOHAM-15572 || replacing deprecated sfdx commands

force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/classes/ESA_cls_caseTriggerHandlerTest.cls, force-app/main/default/triggers/CaseTrigger.trigger
On Behalf of Rahul's changes EDRD-338
=> On Behalf of Rahul's changes EDRD-338

force-app/main/default/classes/ODRIntegration.cls
Fetch Prescription History Method Modified to handle the entire prescription history data.
=> BCMOHAD-20556 Fetch Prescription History method modified

force-app/main/default/classes/EDRDAccountLookupController.cls, force-app/main/default/layouts/MedicationRequest-EDRD_Medication_Request_Layout.layout-meta.xml
SIT Defect of EDRD-446 and UAT Defect Story EDRD-597
=> SIT Defect of EDRD-446 and UAT Defect Story EDRD-597

OmniStudio-Components/main/default/omniDataTransforms/EDRDDRcreateRequestWithNoEligiblity_1.rpt-meta.xml, OmniStudio-Components/main/default/omniDataTransforms/EDRDDRcreateRequestWithNoSupplementoryDoc_1.rpt-meta.xml
OS UAT Defect fix on behalf  of Vinayak
=> OS UAT Defect fix on behalf  of Vinayak

sfdx-project.json
Updating package version number
=> BCMOHAD-14901 || updating package version number

sfdx-project.json
Updating package version number
=> BCMOHAD-14901 || increment version

sfdx-project.json
=> BCMOHAD-14901 || increment package version

force-app/main/default/objects/Case/listViews/My_EDRD_Close_Cases.listView-meta.xml, force-app/main/default/objects/Case/listViews/My_EDRD_Open_Cases.listView-meta.xml
=> EDRD-546 & 547 defect fix

.github/workflows/deploy-to-edrdqa.yml, sfdx-project.json
Updating sfdx-project.json file to fix retrieving source issue 
Fixing EDRD-QA deployment issue
=> BCMOHAM-14323 || adding OS to packageDirectories

dev-app-post/main/default/profiles/Admin.profile-meta.xml
Access to Admins for below fields:
EDRD_Case_Fits_Criteria__c
EDRD_Case_Reason_Does_Not_Meet_Criteria__c
EDRD_MOHFunding_Decision__c
EDRD_MOHFunding_Start_Date__c
EDRD_SC_Review_Funding_Duration_Unit__c
EDRD_RPH_Review_Funding_Duration_Unit__c
EDRD_AC_Review_Funding_Duration_Unit__c
=> 399v3 - admin access

.github/workflows/deploy-to-edrdqa.yml, .github/workflows/deploy-to-edrduat.yml
Adding ignore conflicts flag to dev-app-pre folder
=> BCMOHAM-14323 || added ignore conflicts flag

force-app/main/default/omniScripts/MyozymeInitialSubmission_MyozymeInitialSubmission_English_2.os-meta.xml
=> activating EDRD 19 eform

force-app/main/default/omniScripts/MyozymeInitialSubmission_MyozymeInitialSubmission_English_2.os-meta.xml
=> EDRD-19 activate

force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml
=> Flow Defect fix

force-app/main/default/customPermissions/EDRD_PHSA_PSP_Staff.customPermission-meta.xml, force-app/main/default/objects/Account/validationRules/EDRD_PHSA_PSP_STAFF_Birthdate.validationRule-meta.xml, force-app/main/default/objects/Account/validationRules/EDRD_PHSA_PSP_STAFF_Patient_Identifier.validationRule-meta.xml, force-app/main/default/objects/Account/validationRules/EDRD_PHSA_PSP_STAFF_Provider_Identifier.validationRule-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml
=> 492 bugs fix

.github/workflows/deploy-to-edrdqa.yml, .github/workflows/deploy-to-edrduat.yml
Updating EDRD deployment scripts
=> BCMOHAM-14323 || updating sf project deploy start commands

force-app/main/default/objects/Medication/fields/Initial_Recommended_Dosage__c.field-meta.xml, force-app/main/default/objects/Medication/fields/Renewal_Recommended_Dosage__c.field-meta.xml
Field type change for medication
=> Field type change for medication

.github/workflows/deploy-to-edrdqa.yml, .github/workflows/deploy-to-edrduat.yml, dev-app-post/main/default/profiles/Service Account Profile.profile-meta.xml, force-app/main/default/profiles/Service Account Profile.profile-meta.xml
1.Updating PR based on best practice of SF and Source first policy. 
Link to SF acticle: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_tracking_resolve_conflicts.htm
2.Deactivating retired setting "Allow user to train and generate models for Object Detection"
=> BCMOHAM-14323 || adding ignore conflicts flag

.github/pull_request_template.md, .github/workflows/create-build.yml
1.Updating Node.js to 20
2.Adding PR template to SAT git repository to standardize the information that github contributers need to include when they open issues. @cgijeffolsen @cgiSunilM Please review the Template for PRs, and if you have any suggestions, I am open to them. Thank you!
=> BCMOHAM-14323 || Updating node.js, Adding PR template

.github/workflows/Manual Build Check.yml, .github/workflows/build-checks.yml
Migrating GitHub Actions to the latest Node version. These changes were completed to align with GitHub recommendations. 
[BCMOHAD-20880](https://proactionca.ent.cgi.com/jira/browse/BCMOHAD-20880) SAT - Node.js warning in YML file
GitHub Action workflows: 
Manual Build Check.yml
build-checks.yml
=> BCMOHAD-20880 || Transitioning from Node 16 to Node 20

force-app/main/default/classes/EDRDAccountContactShare.cls, force-app/main/default/classes/EDRDAccountContactShare.cls-meta.xml, force-app/main/default/classes/EDRDAccountContactShare_Test.cls, force-app/main/default/classes/EDRDAccountContactShare_Test.cls-meta.xml, force-app/main/default/classes/EDRDMedicationReqwithACRHandler.cls, force-app/main/default/classes/EDRDMedicationReqwithACRHandler.cls-meta.xml, force-app/main/default/classes/EDRDShareMedicationReqwithAccCon_Test.cls, force-app/main/default/classes/EDRDShareMedicationReqwithAccCon_Test.cls-meta.xml, force-app/main/default/flows/Account_Contact_Case_Share.flow-meta.xml
=> Edrd 491 & 334

dev-app-post/main/default/profiles/Admin.profile-meta.xml, dev-app-post/main/default/profiles/EDRD Prescriber Community User.profile-meta.xml, force-app/main/default/classes/EDRD_cls_CarePgmEnrolleeHandler.cls, force-app/main/default/flows/Create_EDRD_Case.flow-meta.xml, force-app/main/default/objects/CareProgramEnrollee/fields/AccountId.field-meta.xml, force-app/main/default/objects/CareProgramEnrollee/validationRules/EDRD_Check_Name_Value.validationRule-meta.xml
=> Fix EDRD-403

force-app/main/default/dashboards/PreconfiguredServiceCloudDashboards.dashboardFolder-meta.xml, force-app/main/default/dashboards/SAQA.dashboardFolder-meta.xml, force-app/main/default/dashboards/SAstatsdashboard.dashboardFolder-meta.xml, force-app/main/default/dashboards/Sales_and_Marketing_Dashboards.dashboardFolder-meta.xml, force-app/main/default/dashboards/Service_Dashboards.dashboardFolder-meta.xml, force-app/main/default/reports/DBAACminutes.reportFolder-meta.xml, force-app/main/default/reports/Daily_TL_checks.reportFolder-meta.xml, force-app/main/default/reports/DashboardReportsAdoption.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedCompanyKPI.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedServiceAgent.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedServiceExecOverview.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedServiceManager.reportFolder-meta.xml, force-app/main/default/reports/SAQA.reportFolder-meta.xml, force-app/main/default/reports/SAReports.reportFolder-meta.xml, force-app/main/default/reports/SATReports.reportFolder-meta.xml, force-app/main/default/reports/Sales_Marketing_Reports.reportFolder-meta.xml, force-app/main/default/reports/Sales_and_Marketing_Reports.reportFolder-meta.xml, force-app/main/default/reports/Service_Dashboards_Reports.reportFolder-meta.xml, sfdx-project.json
Updated the **Reports** Sharing settings: Given Manage access to the creator and view access to the **"All SAT Team Members"** group
Updated the **Dashboard** Sharing settings: Given Manage access to the creator and view access to the **"All SAT Team Members"** group
Dashboards:
force-app/main/default/dashboards/PreconfiguredServiceCloudDashboards.dashboardFolder-meta.xml
force-app/main/default/dashboards/SAQA.dashboardFolder-meta.xml
force-app/main/default/dashboards/SAstatsdashboard.dashboardFolder-meta.xml
force-app/main/default/dashboards/Sales_and_Marketing_Dashboards.dashboardFolder-meta.xml
force-app/main/default/dashboards/Service_Dashboards.dashboardFolder-meta.xml
Reports:
force-app/main/default/reports/DBAACminutes.reportFolder-meta.xml …
=> BCMOHAM-15625-V3 || Reports and Dashboards

dev-app-post/main/default/profiles/Admin.profile-meta.xml, force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/classes/ESA_cls_caseTriggerHandlerTest.cls, force-app/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/layouts/Case-EDRD Layout.layout-meta.xml, force-app/main/default/objects/Case/fields/EDRD_Bypass_Eligibility_Form__c.field-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Standard_User.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> Eligibility form bypass

force-app/main/default/triggers/MedicationRequestTrigger.trigger
=> Removing commented code

force-app/main/default/objects/Case/fields/EDRD_Case_Eligible_For_Rph_Review__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_Patient_Meets_Criteria_for_Rph__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_RPH_Patient_Not_Meet_Criteria__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_RPH_Review_Funding_Duration_Unit__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_RPH_Review_Funding_Duration__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_RPH_Review_Notes__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_RPH_Review_Pathway__c.field-meta.xml, force-app/main/default/objects/Case/fields/EDRD_RPH_Simplified_Review__c.field-meta.xml, force-app/main/default/objects/OmniScriptSavedSession/OmniScriptSavedSession.object-meta.xml, force-app/main/default/objects/OmniScriptSavedSession/fields/Draft_Name__c.field-meta.xml, force-app/main/default/objects/OmniScriptSavedSession/listViews/My_Drafts.listView-meta.xml
=> OmniScript Saved Session

force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/classes/ESA_cls_caseTriggerHandlerTest.cls
=> Add try block

OmniStudio-Components/main/default/permissionsets/EDRD_OmniStudio_Experience_Users.permissionset-meta.xml, force-app/main/default/customPermissions/EDRD_MOH_STAFF.customPermission-meta.xml, force-app/main/default/customPermissions/EDRD_PHSA_PSP_Staff.customPermission-meta.xml
=> Field permission and others

.github/workflows/deploy-to-build.yml, .github/workflows/deploy-to-staging.yml
Updating YML Scripts to facilitate deployments of OmniStudio components to Staging and Production
[BCMOHAM-14323](https://proactionca.ent.cgi.com/jira/browse/BCMOHAM-14323) 
deploy-to-build.yml
deploy-to-staging.yml
=> BCMOHAM-14323 || Updating Deployment Scripts 

force-app/main/default/objects/OmniScriptSavedSession/listViews/My_Drafts.listView-meta.xml
=> List view filter chnages

dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml, force-app/main/default/classes/ESA_cls_accountTriggerHandler.cls, force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/triggers/CaseTrigger.trigger, force-app/main/default/triggers/ESA_tgr_accountTrigger.trigger
Reverted the changes in Triggers.
Added the conditions in Handler Classes
Updated the Profile
dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml
force-app/main/default/classes/ESA_cls_accountTriggerHandler.cls
force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls
force-app/main/default/triggers/CaseTrigger.trigger
force-app/main/default/triggers/ESA_tgr_accountTrigger.trigger
=> BCMOHAM-15625-V5 || Reverted the changes in Triggers

.github/workflows/build-checks.yml, OmniStudio-Components/main/default/AssessmentQuestions/Test_Assessment_Question.aq-meta.xml, sfdx-project.json
Resolving merge conflicts 
[BCMOHAM-15625](https://proactionca.ent.cgi.com/jira/browse/BCMOHAM-15625)
sfdx-project.json 
build-check.yml
OmniStudio-Components folder
=> BCMOHAM-15625 || Resolving merge conflicts 

force-app/main/default/dashboards/PreconfiguredServiceCloudDashboards.dashboardFolder-meta.xml, force-app/main/default/dashboards/SAQA.dashboardFolder-meta.xml, force-app/main/default/dashboards/SAstatsdashboard.dashboardFolder-meta.xml, force-app/main/default/dashboards/Sales_and_Marketing_Dashboards.dashboardFolder-meta.xml, force-app/main/default/dashboards/Service_Dashboards.dashboardFolder-meta.xml, force-app/main/default/groups/SAT_Admin.group-meta.xml, force-app/main/default/reports/DBAACminutes.reportFolder-meta.xml, force-app/main/default/reports/Daily_TL_checks.reportFolder-meta.xml, force-app/main/default/reports/DashboardReportsAdoption.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedCompanyKPI.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedServiceAgent.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedServiceExecOverview.reportFolder-meta.xml, force-app/main/default/reports/GettingStartedServiceManager.reportFolder-meta.xml, force-app/main/default/reports/SAQA.reportFolder-meta.xml, force-app/main/default/reports/SAReports.reportFolder-meta.xml, force-app/main/default/reports/SATReports.reportFolder-meta.xml, force-app/main/default/reports/Sales_Marketing_Reports.reportFolder-meta.xml, force-app/main/default/reports/Sales_and_Marketing_Reports.reportFolder-meta.xml, force-app/main/default/reports/Service_Dashboards_Reports.reportFolder-meta.xml
Created the new public group and changed tye sharing settings of the reports and dashboards..
Public Group:
force-app/main/default/groups/SAT_Admin.group-meta.xml
Dashboards:
force-app/main/default/dashboards/PreconfiguredServiceCloudDashboards.dashboardFolder-meta.xml
force-app/main/default/dashboards/SAQA.dashboardFolder-meta.xml
force-app/main/default/dashboards/SAstatsdashboard.dashboardFolder-meta.xml
force-app/main/default/dashboards/Sales_and_Marketing_Dashboards.dashboardFolder-meta.xml
force-app/main/default/dashboards/Service_Dashboards.dashboardFolder-meta.xml
Reports:
force-app/main/default/reports/DBAACminutes.reportFolder-meta.xml
force-app/main/default/reports/Daily_TL_checks.reportFolder-meta.xml
force-app/main/default/reports/DashboardReportsAdoption.reportFolder-meta.xml …
=> BCMOHAM-15625-V8 || Created new public group and updated the sharing settings of the Reports

force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml
=> Permission Set update for RUN Flows

sfdx-project.json
=> Update project Sfdx Id

dev-app-post/main/default/classes/ESA_cls_caseTriggerHandlerTest.cls, dev-app-post/main/default/profiles/Admin.profile-meta.xml, force-app/main/default/classes/EDRD_cls_ShowToastMsgController.cls, force-app/main/default/classes/EDRD_cls_ShowToastMsgController.cls-meta.xml, force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/labels/CustomLabels.labels-meta.xml, force-app/main/default/layouts/Case-EDRD Layout.layout-meta.xml, force-app/main/default/layouts/Medication-EDRD Portal Medication Layout.layout-meta.xml, force-app/main/default/lwc/eDRD_LC_ShowToastMessageOnCase/eDRD_LC_ShowToastMessageOnCase.html, force-app/main/default/lwc/eDRD_LC_ShowToastMessageOnCase/eDRD_LC_ShowToastMessageOnCase.js, force-app/main/default/lwc/eDRD_LC_ShowToastMessageOnCase/eDRD_LC_ShowToastMessageOnCase.js-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Operational_Support.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Standard_User.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml, force-app/main/default/triggers/CaseTrigger.trigger, force-app/main/default/triggers/CaseTrigger.trigger-meta.xml
Development Related to EDRD-764, 731.
=> EDRD-764, 731

sfdx-project.json
Increment package version ID. 
User Story: SAT - DIN Filter Issue
=> BCMOHAD-23176 || Increment package version ID

dev-app-post/main/default/settings/Case.settings-meta.xml
PR to fix the deployment error:
Error Case EmailToCaseRoutingAddress[Default Support Email]: isVerified is a read only field and cannot be changed
=> BCMOHAD-23176 - Stg deployment fix

dev-app-post/main/default/assignmentRules/Case.assignmentRules-meta.xml, force-app/main/default/queueRoutingConfigs/cases_Routing_config.queueRoutingConfig-meta.xml, force-app/main/default/queues/General_Queue.queue-meta.xml
=> Assignment rules

sfdx-project.json
=> BCMOHAD-24614 || updating package version id

force-app/main/default/classes/QueueOwnerSetterTest.cls, sfdx-project.json
Removing the General_Queue and updating it with Migraine_Queue since it is present in the GIT
force-app/main/default/classes/QueueOwnerSetterTest.cls
=> BCMOHAD-24466 || changing from General_Queue to Migraine_Queue

.github/workflows/build-checks.yml
=> BCMOHAM-19482 || adding deployment command to install the IAM package into scratch org

sfdx-project.json
Committing sfdx-project.json file to resolve the error while promoting 2G Unlocked package
=> BCMOHAM-17688 || creating pckg version ID for Prod Release

dev-app-post/main/default/email/unfiled$public/EDRDPortalCommunityWelcomeEmailTemplate.email, dev-app-post/main/default/email/unfiled$public/EDRDPortalCommunityWelcomeEmailTemplate.email-meta.xml
Changes related - Welcome email configuration for EDRD-Portal
=> Changes related - Welcome email configuration for EDRD-Portal

sfdx-project.json
=> Updated the Version name and number

sfdx-project.json
=> BCMOHAD-26578 || updating sfdx-project.json

.github/workflows/build-checks.yml
As a prerequisite to add IAM components to git repo, IAM and HealthCloud packages need to be installed into scratch org to ensure a validation check is successful.  
=> BCMOHAD-26773 || updating build check.yml

force-app/main/default/reports/UserSetup.reportFolder-meta.xml
**User Setup Reports Folder is shared with SAT_Admin Public group members.**
Fixes # (BCMOHAD-26782)
**User Setup Reports Folder Sharing updated.
SA Admin Public group members will have manage access to the User Setup Reports Folder.**
https://github.com/bcgov/MoH-SAT/pull/1391
=> BCMOHAD-26782

dev-app-post/main/default/flows/Create_EDRD_Case.flow-meta.xml
Updated the flow by adding a new fault line screen to show the EDRD Staff the exact error message
dev-app-post/main/default/flows/Create_EDRD_Case.flow-meta.xml
=> BCMOHAM-21220 || Updated the flow with new error messages

force-app/main/default/permissionsets/Salesforce_Backup_Administrator.permissionset-meta.xml, sfdx-project.json
While deploying to Staging, the error has been occured: Salesforce_Backup_Administrator: In field: object - no CustomObject named AlternativePaymentMethod found
Removing objects related to Order management from SF Backup Administrator permission set. Creating a new package version ID. 
=> BCMOHAD-26578 || Updating sfdx project json file

force-app/main/default/objects/Case/fields/EDRD_ProviderName__c.field-meta.xml, force-app/main/default/objects/Case/fields/Reason__c.field-meta.xml
=> EDRD-1091CF

force-app/main/default/objects/Case/fields/EDRD_EMPI_Override_Reason_Renewal__c.field-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Operational_Support.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Physicians.permissionset-meta.xml
=> EDRD-1060V1

force-app/main/default/queues/EDRD_Ministry_Queue.queue-meta.xml, force-app/main/default/queues/EDRD_PSP_Queue.queue-meta.xml
I have unchecked the option of “Send Email to Members” from the EDRD Queues as hotfix in production and I have created a PR with the same changes.
cc: @deepakmulamalla 
Fixes # BCMOHAM-21891
- [ Yes] Bug fix (non-breaking change which fixes an issue)
=> BCMOHAM-21891- Send email to members option unchecked in the EDRD Queues

force-app/main/default/layouts/Case-SA Request.layout-meta.xml, force-app/main/default/permissionsets/SA_Manager_PS.permissionset-meta.xml
Created the new Permission set for SA Manager PS and updated the fields and removed the Pushed to PNET field edit access for SA Staff 
**Post Deployment Steps:**
Once Deployed add the SA Manager PS to the users Vern McIntosh, Cheryl Burton, Stephanie Sancho and Sonia Drummond and remove their SA Admin permission set
force-app/main/default/layouts/Case-SA Request.layout-meta.xml
force-app/main/default/permissionsets/MoH_Standard_User.permissionset-meta.xml
force-app/main/default/permissionsets/SA_Manager_PS.permissionset-meta.xml
=> BCMOHAD-25690 || Updated the changes for permission sets

force-app/main/default/classes/medicinalIngredientTriggerHandlerTest.cls
=> BCMOHAD-25690 - Package Creation error fix

sfdx-project.json
=> BCMOHAD-27459 - incrementing version number and creating pkg version ID

OmniStudio-Components/main/default/omniScripts/EDRD_RenewForm_English_1.os-meta.xml, force-app/main/default/staticresources/EMP_Patient_UI_enhancement_V14.css, force-app/main/default/staticresources/EMP_Patient_UI_enhancement_V14.resource-meta.xml
=> Edrd 1070 v1

OmniStudio-Components/main/default/omniScripts/EDRDNewForm_EDRDNewForm_English_1.os-meta.xml
=> EDRD-1255V2

dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml
=> EDRD-90V3UAT

force-app/main/default/classes/EDRD_EmpiIntegration.cls, force-app/main/default/classes/EDRD_EmpiWrapper.cls, force-app/main/default/classes/ESA_cls_constants.cls, force-app/main/default/permissionsets/EDRD_PS_Reviewer.permissionset-meta.xml
=> EDRD-1160UAT

.github/workflows/deploy-to-edrdqa2.yml
Deployment Automation for EDRDQA2
=> BCMOHAD-27526 || Create github actions for automatic deployments to edrdqa2

.github/workflows/deploy-to-edrddev3.yml
Deployment Automation for EDRDDev3
=> BCMOHAD-27526 || Create github actions for automatic deployments

force-app/main/default/tabs/Pharmanet_Payload__c.tab-meta.xml
=> edrd-1207V2

dev-app-post/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml, force-app/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml
=> EDRD-1207AccessMissing

force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml
=> EDRD-UAT-1271

force-app/main/default/objects/ServiceAppointment/fields/EDRD_Meeting_URL__c.field-meta.xml
=> EDRD-1271-1275

force-app/main/default/layouts/Pharmanet_Payload__c-Pharmanet Payload Layout.layout-meta.xml
=> EDRD-1342-QA

.forceignore, dev-app-post/main/default/flows/Create_EDRD_Case.flow-meta.xml
=> Changes related EDRD-1349

force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Operational_Support.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> EDRD-1242-QA

.forceignore, force-app/main/default/classes/EmpiIntegration.cls, sfdx-project.json
=> BCMOHAD-23189- package Creation Fix

OmniStudio-Components/main/default/omniScripts/EDRDNewForm_EDRDNewForm_English_28.os-meta.xml
=> EDRD-1325-UATDefects

OmniStudio-Components/main/default/omniScripts/EDRDNewForm_EDRDNewForm_English_28.os-meta.xml, OmniStudio-Components/main/default/omniScripts/EDRD_RenewForm_English_7.os-meta.xml
=> EDRD-1348-1350-UATDefects

dev-app-post/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/layouts/Case-EDRD Layout.layout-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Operational_Support.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Physicians.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Reviewer.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> EDRD-1222 QA

force-app/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> EDRD-1342-toQA

force-app/main/default/animationRules/EC_Path.animationRule-meta.xml
To reduce the no.of post-deployment steps we have updated the Animation rules/Path Settings from **Often** to **Always**
force-app/main/default/animationRules/EC_Path.animationRule-meta.xml
=> BCMOHAD-28087 || Updated the frequency from often to Always

OmniStudio-Components/main/default/omniScripts/CrysvitaInitialSubmission_CrysvitaInitialSubmission_English_1.os-meta.xml, OmniStudio-Components/main/default/omniScripts/GaucherInitialSubmission_gaucherInitialSubmission_English_1.os-meta.xml, OmniStudio-Components/main/default/omniScripts/ProcysbiInitialSubmission_ProcysbiInitialSubmission_English_1.os-meta.xml, dev-app-post/main/default/experiences/EDRDPortal1/views/sANDOZMIGLUSTATRENEWALSUBMISSION.json, force-app/main/default/classes/OmniScriptSavedSessionTriggerHandlerTest.cls, force-app/main/default/classes/OmniScriptSavedSessionTriggerHandlerTest.cls-meta.xml
=> EDRD-1381, EDRD-1382

dev-app-post/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/classes/EDRD_PharmanetPayload.cls, force-app/main/default/classes/EDRD_PharmanetWrapper.cls, force-app/main/default/flexipages/EDRD_Case_record_page.flexipage-meta.xml, force-app/main/default/permissionsets/EDRD_PS_MOH_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_Operational_Support.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_PS_PHSA_PSP_Staff.permissionset-meta.xml, force-app/main/default/permissionsets/EDRD_Super_User.permissionset-meta.xml
=> EDRD-QA-1342

force-app/main/default/flexipages/Pharmanet_Payload_Record_Page.flexipage-meta.xml
=> EDRD-QA-1341V1

dev-app-post/main/default/sharingRules/Pharmanet_Payload__c.sharingRules-meta.xml, force-app/main/default/objects/Pharmanet_Payload__c/Pharmanet_Payload__c.object-meta.xml
=> EDRD-1354-V3

force-app/main/default/classes/ContentVersionBatch.cls, force-app/main/default/classes/ContentVersionBatch.cls-meta.xml, force-app/main/default/classes/ContentVersionBatchScheduler.cls, force-app/main/default/classes/ContentVersionBatchScheduler.cls-meta.xml, force-app/main/default/classes/ContentVersionBatchSchedulerTest.cls, force-app/main/default/classes/ContentVersionBatchSchedulerTest.cls-meta.xml, force-app/main/default/classes/ContentVersionBatchTest.cls, force-app/main/default/classes/ContentVersionBatchTest.cls-meta.xml
Created a new Batch and Scheduler class to run for every 6 hours i.e., 4 times a day.
**One-Time Post-Deployment Step:**
Open Developer Console, In the **Debug** select **Open Execute Anonymous Window** 
Paste the following code and Execute it:
**String cronExp = '0 0 0,6,12,18 * * ?'; 
System.schedule('ContentVersionBatchJob', cronExp, new ContentVersionBatchScheduler());**
To confirm the execution In Setup, search for Scheduled Jobs, once we are in Scheluded Jobs we can see **ContentVersionBatchJob** Activated.
force-app/main/default/classes/ContentVersionBatch.cls
force-app/main/default/classes/ContentVersionBatchTest.cls
force-app/main/default/classes/ContentVersionBatchScheduler.cls
force-app/main/default/classes/ContentVersionBatchSchedulerTest.cls
=> BCMOHAD-28145 || Created new Batch and Scheduler classes

force-app/main/default/classes/ContentVersionBatch.cls, force-app/main/default/classes/ContentVersionBatch.cls-meta.xml
Updated the class with Trim and Truncate
force-app/main/default/classes/ContentVersionBatch.cls
=> BCMOHAD-28193 || Updated the class with Trim and Truncate

force-app/main/default/objects/Drug_Template__c/fields/Excluded_Plans__c.field-meta.xml, force-app/main/default/objects/Step_Action__c/fields/Excluded_Plans__c.field-meta.xml, force-app/main/default/objects/Step_Action__c/recordTypes/ESA_RT_Case_Update.recordType-meta.xml, force-app/main/default/objects/Step_Action__c/recordTypes/Pharmanet_Payload.recordType-meta.xml
Updated the NP picklist value in the Excluded Plans Field
force-app/main/default/objects/Drug_Template__c/fields/Excluded_Plans__c.field-meta.xml
force-app/main/default/objects/Step_Action__c/fields/Excluded_Plans__c.field-meta.xml
force-app/main/default/objects/Step_Action__c/recordTypes/ESA_RT_Case_Update.recordType-meta.xml
force-app/main/default/objects/Step_Action__c/recordTypes/Pharmanet_Payload.recordType-meta.xml
=> BCMOHAM-23301 || Updated the NP value int picklist value

dev-app-post/main/default/classes/EDRD_SendNewCaseCreationNotif_Test.cls, dev-app-post/main/default/classes/EDRD_SendNewCaseCreationNotif_Test.cls-meta.xml, dev-app-post/main/default/classes/EDRD_SendNewCaseCreationNotification.cls, dev-app-post/main/default/classes/EDRD_SendNewCaseCreationNotification.cls-meta.xml, dev-app-post/main/default/flows/Create_EDRD_Case.flow-meta.xml
BCMOHAM-23087- Updateflow to send notification to queue
Fixes # (BCMOHAM-23087)
=> BCMOHAM-23087- Updateflow to send notification to queue

force-app/main/default/lwc/patientLookup/patientLookup.html, force-app/main/default/lwc/patientLookup/patientLookup.js
Production Issue : Declared name displaying twice on the UI- fixed. By rendering the declared name and documented based on the response params.( LRA and traditional EMPI).
Unit tested the Issue in phaq1 environment by passing the JSON load to replicate the scenario.
https://github.com/bcgov/MoH-SAT/pull/1544
=> BCMOHAD-28178

force-app/main/default/classes/ESA_cls_caseTriggerHandler.cls, force-app/main/default/classes/ESA_cls_constants.cls
=> EDRD-1354V5

.github/workflows/deploy-to-staging.yml
Reverting the changes to allow a successful build 
=> BCMOHAD-28236 || reverting changes

OmniStudio-Components/main/default/omniScripts/EDRDNewForm_EDRDNewForm_English_30.os-meta.xml, OmniStudio-Components/main/default/omniScripts/EDRD_RenewForm_English_16.os-meta.xml
=> EDRD-1405-V1

OmniStudio-Components/main/default/omniScripts/BrineuraInitialSubmission_BrineuraInitialSubmission_English_1.os-meta.xml, OmniStudio-Components/main/default/omniScripts/OrladeyoInitialSubmission_OrladeyoInitialSubmissionDesc_English_1.os-meta.xml, OmniStudio-Components/main/default/omniScripts/SpinrazaRenewalSubmission_SpinrazaRenewalSubmissionDesc_English_1.os-meta.xml
=> FutureDateIssues

OmniStudio-Components/main/default/omniScripts/EDRD_RenewForm_English_16.os-meta.xml
=> EDRD-1434V2

OmniStudio-Components/main/default/omniScripts/OrladeyoRenewalSubmission_OrladeyoRenewalSubmissionDesc_English_1.os-meta.xml
=> EDRD-1429V1

docs/development/dev-tips.md
=> BCMOHAD-27526 || Alignment with edrd changes 

sfdx-project.json
Updating sfdx-project .json file 
=> BCMOHAD-28236 || Updated package version ID

OmniStudio-Components/main/default/omniScripts/AmvuttraRenewalSubmission_AmvuttraRenewalSubmission_English_1.os-meta.xml
=> EDRD-1196V2

OmniStudio-Components/main/default/omniScripts/EDRD_RenewForm_English_18.os-meta.xml
=> EDRD-1458V2

sfdx-project.json
This package version ID contains the changes from PR 1596.
=> BCMOHAD-28606 || new package version id

OmniStudio-Components/main/default/omniScripts/MiglustatNPCInitialSubmission_MiglustatNPCInitialSubmission_English_1.os-meta.xml, dev-app-post/main/default/permissionsets/EDRD_Physician_Medication_Management.permissionset-meta.xml, force-app/main/default/classes/medicationRequestTriggerHandler.cls
=> EDRD-1462-QA

sfdx-project.json
updating sfdx project json file 
=> BCMOHAD-28606 || updated package id

sfdx-project.json
=> BCMOHAD-28606 || Updating json file

.github/workflows/Manual Build Check.yml, .github/workflows/build-checks.yml, .github/workflows/deploy-to-staging.yml
=> BCMOHAD-28994 || Script optimization

OmniStudio-Components/main/default/omniDataTransforms/EDRDDRextractloginuserid_1.rpt-meta.xml, OmniStudio-Components/main/default/omniScripts/EDRDNewForm_EDRDNewForm_English_30.os-meta.xml
=> EDRD-UAT-Defects

config/project-scratch-def.json, dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml, force-app/main/default/objects/AssessmentQuestionVersion/AssessmentQuestionVersion.object-meta.xml
Updated the Profile record type and Page layout visibility in **Account** object for **MoH Standard User** Profile
dev-app-post/main/default/profiles/MoH Standard User.profile-meta.xml
=> BCMOHAD-29214 || Updated the Profile record type and Page layout

force-app/main/default/classes/ExternalCommitteeAlert.cls
Updated the changes for back promotion from the production to the lower environments.
force-app/main/default/classes/ExternalCommitteeAlert.cls
=> BCMOHAM-25136 || Updated the org wide Name to match the Production

docs/development/dev-tips.md
Updating Configuration steps for EDRD test integration instances 
=> BCMOHAD-28606 || Updating github documentation for alignment with the recent changes

dev-app-post/main/default/classes/LightningForgotPasswordControllerTest.cls, force-app/main/default/classes/FeedItemTrigger_Test.cls, force-app/main/default/classes/FeedItemTrigger_Test.cls-meta.xml, force-app/main/default/classes/RelatedFilesTest.cls, force-app/main/default/classes/RelatedFilesTest.cls-meta.xml
Bcmohad 29032 - Update test class increase coverage 
Fixes # (BCMOHAD-29032)
=> Bcmohad 29032

force-app/main/default/objects/Step_Action__c/fields/Adjudication_Status__c.field-meta.xml
Added new picklist values to the field **Adjudication_Status__c** in the Step Action object:
**Post Deployment Steps:**
Update the **Adjudication** record type with newly added picklist values for the field Adjudication_Status__c:
Under Review
Received
force-app/main/default/objects/Step_Action__c/fields/Adjudication_Status__c.field-meta.xml
=> BCMOHAD-29371 || Updated the picklist values

OmniStudio-Components/main/default/omniDataTransforms/getACRDetails_1.rpt-meta.xml
=> EDRD-1417V2

.github/workflows/deploy-to-edrdqa.yml
=> BCMOHAD-29305 || Updating the script to ensure changes are reflected on the Experience Site

force-app/main/default/permissionsets/SA_Administrator_AdminPermissions.permissionset-meta.xml
=> BCMOHAD-28994 || package error fix

force-app/main/default/permissionsets/SA_Administrator_AdminPermissions.permissionset-meta.xml, sfdx-project.json
=> BCMOHAD-28994 || updated json file

dev-app-post/main/default/classes/EDRD_PharmanetPayloadTest.cls, force-app/main/default/classes/EDRD_EmpiWrapper.cls, force-app/main/default/classes/EDRD_PharmanetPayload.cls, force-app/main/default/classes/EDRD_PharmanetWrapper.cls
=> TestClassCrovage

OmniStudio-Components/main/default/omniScripts/EDRDDeclarationForm_EDRDConsenteForm_English_1.os-meta.xml
EDRD Declaration Date HotFix - 15th September
=> EDRD Declaration Date HotFix
